apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mlops-django
  name: mlops-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-django
  template:
    metadata:
      labels:
        app: mlops-django
    spec:
      containers:
      - image: kube4team/test-django-jk:1.0
        name: mlops-django
        ports:
        - containerPort: 8000
