apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-my-release-jenkins-pv-0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /data/jenkins-volume/
