apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-my-release-zookeeper-pv-0
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-zookeeper-0
    namespace: zootopia
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /bitnami/zookeeper

------------------------------------------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-my-release-zookeeper-pv-1
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-zookeeper-1
    namespace: zootopia
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /bitnami/zookeeper
   
------------------------------------------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-my-release-zookeeper-pv-2
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-zookeeper-2
    namespace: zootopia
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /bitnami/zookeeper
